apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stream-app
    spec:
      containers:
        - name: device-app
          image: strimzilab/stream-app:latest