apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: strimzilab/consumer-app:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka:9092"
            - name: CONSUMER_GROUPID
              value: "consumer-app"
            - name: CONSUMER_TOPIC
              value: "iot-temperature-max"
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"